server:
  port: 8001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000

spring:
  datasource:
    druid:
      max-active: 200
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      min-idle: 1
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: eurake-server
